name: language-auto
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
      - name: docker 
        run: | 
          docker network create untitest_network 
          docker run --name mysql-docker --network untitest_network -e MYSQL_ROOT_PASSWORD=sallatest -d mysql
          docker exec -i  mysql-docker sh -c "echo hellow world"
          curl https://salla-dev.s3.eu-central-1.amazonaws.com/d222212222/e7d401a3636bb58321269d64ac925d3e/utdb.sql | docker exec -i mysql-docker /bin/bash -c " mysql -h localhost -uroot -psallatest -f "

      - name: Importing Testing DB
        continue-on-error: true
        run: |
          docker ps 
          
      - name: show database 
        run: |
          docker exec -i mysql-docker mysql -e 'show databases;' -h localhost -uroot -psallatest -f
