name: language-auto
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
      - name: docker 
        run: | 
          docker network create untitest_network 
          docker run --name mysql-docker --network untitest_network -e MYSQL_ROOT_PASSWORD=sallatest  -d mysql:5.7
          docker run --name redis --network untitest_network -d redis

          while ! docker exec mysql-docker mysql --user=root --password=sallatest -e "status" &> /dev/null ; do
              echo "Waiting for database connection..."
              sleep 2
          done   
         
          while ! docker exec redis redis-cli ping -e "pong" &> /dev/null ; do
              echo "Waiting for redis connection..."
              sleep 2
          done   
          
          docker exec -i  mysql-docker sh -c "echo hellow world"
          docker exec -i  mysql-docker sh -c "mysql -uroot -psallatest -e 'show databases'"
      - name: Importing Testing DB
        continue-on-error: true
        run: |
          docker ps 
          
      - name: show database 
        run: |
          curl https://salla-dev.s3.eu-central-1.amazonaws.com/d222212222/e7d401a3636bb58321269d64ac925d3e/utdb.sql | docker exec -i mysql-docker /bin/bash -c " mysql -h localhost -uroot -psallatest -f "

          docker exec -i mysql-docker mysql -e 'show databases;' -h localhost -uroot -psallatest -f
